### ISSUE TITLE
seminar 2

### ISSUE THREAD

**Issue by daehwan2da** [GO-SOPT-ANDROID/daehwan.gye#2]
## TODO
- [ ] RecyclerView
  - [ ] Adaptor 에대해 공부하기
- [ ] Viewmodel
  - [ ] share 영상 보고 공부하기
- [ ] Scroll
- [ ] BottomNavigation
- [ ] about Fragment 

## 개인..
- [ ] context 에 대해 알아보기
  - [ ] fragment 와 Activity 에서 context
